### PR TITLE
Bump grunt-lib-phantomjs-istanbul version

### PR DESCRIPTION
**Pull request by apsdehal**
- Use 1.0.0

### CODE REVIEW

**Comment by apsdehal** [comment]
@asciidisco Any updates on this?

**Comment by PMPP** [comment]
👍

**Comment by leobalter** [comment]
@apsdehal I can't get your branch to be merged manually anymore. This is probably going to be overridden by #60

**Comment by leobalter** [comment]
I'm sorry for this delay.

**Pull request closed without merging**
